---
- name: Copy private key
  copy:
    dest: '{{ jail_home.stdout }}/usr/local/etc/namedb/keys/K{{ item.0 }}.+{{ "00{}".format(bind_dnssec[item.0][item.1].algorithm)[-3:] }}+{{ bind_dnssec[item.0][item.1].private'
    content: '{{ bind_dnssec[item.0][item.1].private_key }}'
    owner: root
    group: bind
    mode: 0640
  with_nested:
    - '{{ bind_dnssec }}'
    - [ 'ksk', 'zsk' ]

- name: Copy public key
  template:
    src: public.key.j2
    dest: '{{ jail_home.stdout }/usr/local/etc/namedb/K{{ item.0 }}.+{{ "00{}".format(bin_dnssec[item.0][item.1].algorithm)[-3:] }}+{{ bind_dessec[item.0][item.1].tag }}.key'
    owner: root
    group: bind
    mode: 0640
  with_nested:
    - '{{ bind_dnssec }}'
    - [ 'ksk', 'zsk' ]

